# Generated by Django 6.0.2 on 2026-02-21 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('assignment_priority', models.IntegerField(default=1)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agencies.securityagency')),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('ack_id', models.AutoField(primary_key=True, serialize=False)),
                ('acknowledged_by', models.CharField(max_length=150)),
                ('ack_timestamp', models.DateTimeField(auto_now_add=True)),
                ('estimated_arrival', models.IntegerField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('responder_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgment', to='alerts.alertassignment')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('TERRORISM', 'Terrorism'), ('BANDITRY', 'Banditry'), ('KIDNAPPING', 'Kidnapping'), ('ARMED_ROBBERY', 'Armed Robbery'), ('OTHER', 'Other')], max_length=20)),
                ('priority_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='CRITICAL', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alertassignment',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='alerts.emergencyalert'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='alerts.emergencyalert')),
            ],
        ),
    ]
