# Generated by Django 6.0.2 on 2026-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_type',
            field=models.CharField(choices=[('TERRORISM', 'Terrorism'), ('BANDITRY', 'Banditry'), ('KIDNAPPING', 'Kidnapping'), ('ARMED_ROBBERY', 'Armed Robbery'), ('FIRE_INCIDENCE', 'Fire Incidence'), ('ACCIDENT', 'Accident'), ('ROBBERY', 'Robbery'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
