# Generated by Django 6.0.2 on 2026-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_emergencyalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
