# Generated by Django 6.0.2 on 2026-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_altitude_city_state_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
