# Generated by Django 6.0.2 on 2026-02-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAgency',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_type', models.CharField(choices=[('POLICE', 'Police'), ('FIRE', 'Fire Service'), ('MEDICAL', 'Medical/Ambulance'), ('MILITARY', 'Military'), ('SECURITY_FORCE', 'Security Force')], max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('jurisdiction', models.TextField()),
                ('operational_capacity', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DISPATCHER', 'Dispatcher'), ('RESPONDER', 'Responder'), ('COMMANDER', 'Commander')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='agencies.securityagency')),
            ],
        ),
    ]
